image: rikorose/gcc-cmake

build:
  stage: build
  script: 
    - apt-get -y install libcmocka-dev
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  stage: test
  script:
    - make test
