image: dock0/arch

before_script:
  - pacman -S --noconfirm cmake gcc make cmocka jansson lua

build:
  stage: build
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
