dist: xenial
sudo: required
language: c
compiler:
  - gcc
branches:
  only:
    - master
    - dev
before_install:
install:
  - sudo apt-get install -y valgrind libcmocka-dev
before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
script: make && ctest -V -T memcheck && cat Testing/Temporary/MemoryChecker.*.log
