dist: trusty
sudo: required
language: c
install:
  - sudo apt-get install libcmocka-dev
compiler:
  - gcc
before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..
script: make && make test
